name: Build Documentation

on:
  push:
    branches:
      - main
      - cookie # to be removed during merge to main
  pull_request: # to be removed during merge to main
    branches:
      - main
      - cookie
  release:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: # to be removed during merge to main
      contents: write
      pages: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build
          auto-update-conda: true

      - name: install requirements
        run: >-
          conda install -n build -c conda-forge
          --file requirements/build.txt
          --file requirements/run.txt
          --file requirements/docs.txt
          --quiet --yes

      - name: install the package
        run: python -m pip install . --no-deps

      - name: build documents
        run: make -C doc html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
